export const cardConstants = {
    ADD_TITLE: 'ADD_TITLE',
    REMOVE_TITLE: 'REMOVE_TITLE',
    
    CREATE_CARD_REQUEST_STARTED: 'CREATE_CARD_REQUEST_STARTED',
    SUCCESS_CREATE_CARD_REQUEST: 'SUCCESS_CREATE_CARD_REQUEST',
    FAILURE_CREATE_CARD_REQUEST: 'FAILURE_CREATE_CARD_REQUEST',
    CREATE_CARD_REQUEST_ENDED: 'CREATE_CARD_REQUEST_ENDED',

    GET_CARDS_REQUEST_STARTED: 'GET_CARDS_REQUEST_STARTED',
    SUCCESS_GET_CARDS_REQUEST: 'SUCCESS_GET_CARDS_REQUEST',
    FAILURE_GET_CARDS_REQUEST: 'FAILURE_GET_CARDS_REQUEST',
    GET_CARDS_REQUEST_ENDED: 'GET_CARDS_REQUEST_ENDED',
    CLEAR_CARDS_LIST: 'CLEAR_CARDS_LIST',

    GET_CARD_REQUEST_STARTED: 'GET_CARD_REQUEST_STARTED',
    SUCCESS_GET_CARD_REQUEST: 'SUCCESS_GET_CARD_REQUEST',
    FAILURE_GET_CARD_REQUEST: 'FAILURE_GET_CARD_REQUEST',
    GET_CARD_REQUEST_ENDED: 'GET_CARD_REQUEST_ENDED',

    UPDATE_CARD_REQUEST_STARTED: 'UPDATE_CARD_REQUEST_STARTED',
    SUCCESS_UPDATE_CARD_REQUEST: 'SUCCESS_UPDATE_CARD_REQUEST',
    FAILURE_UPDATE_CARD_REQUEST: 'FAILURE_UPDATE_CARD_REQUEST',
    UPDATE_CARD_REQUEST_ENDED: 'UPDATE_CARD_REQUEST_ENDED',
}