export const groupConstants = {
    ADD_TITLE: 'ADD_TITLE',
    REMOVE_TITLE: 'REMOVE_TITLE',
    
    CREATE_GROUP_REQUEST_STARTED: 'CREATE_GROUP_REQUEST_STARTED',
    SUCCESS_CREATE_GROUP_REQUEST: 'SUCCESS_CREATE_GROUP_REQUEST',
    FAILURE_CREATE_GROUP_REQUEST: 'FAILURE_CREATE_GROUP_REQUEST',
    CREATE_GROUP_REQUEST_ENDED: 'CREATE_GROUP_REQUEST_ENDED',

    GET_GROUPS_REQUEST_STARTED: 'GET_GROUPS_REQUEST_STARTED',
    SUCCESS_GET_GROUPS_REQUEST: 'SUCCESS_GET_GROUPS_REQUEST',
    FAILURE_GET_GROUPS_REQUEST: 'FAILURE_GET_GROUPS_REQUEST',
    GET_GROUPS_REQUEST_ENDED: 'GET_GROUPS_REQUEST_ENDED',
    CLEAR_GROUPS_LIST: 'CLEAR_GROUPS_LIST',

    GET_GROUP_REQUEST_STARTED: 'GET_GROUP_REQUEST_STARTED',
    SUCCESS_GET_GROUP_REQUEST: 'SUCCESS_GET_GROUP_REQUEST',
    FAILURE_GET_GROUP_REQUEST: 'FAILURE_GET_GROUP_REQUEST',
    GET_GROUP_REQUEST_ENDED: 'GET_GROUP_REQUEST_ENDED'
}