export const groupConstants = {
    ADD_TITLE: 'ADD_TITLE',
    REMOVE_TITLE: 'REMOVE_TITLE',
    
    CREATE_GROUP_REQUEST_STARTED: 'CREATE_GROUP_REQUEST_STARTED',
    SUCCESS_CREATE_GROUP_REQUEST: 'SUCCESS_CREATE_GROUP_REQUEST',
    FAILURE_CREATE_GROUP_REQUEST: 'FAILURE_CREATE_GROUP_REQUEST',
    CREATE_GROUP_REQUEST_ENDED: 'CREATE_GROUP_REQUEST_ENDED',

    GET_GROUPS_REQUEST_STARTED: 'GET_GROUPS_REQUEST_STARTED',
    SUCCESS_GET_GROUPS_REQUEST: 'SUCCESS_GET_GROUPS_REQUEST',
    FAILURE_GET_GROUPS_REQUEST: 'FAILURE_GET_GROUPS_REQUEST',
    GET_GROUPS_REQUEST_ENDED: 'GET_GROUPS_REQUEST_ENDED',
    CLEAR_GROUPS_LIST: 'CLEAR_GROUPS_LIST',

    GET_GROUP_REQUEST_STARTED: 'GET_GROUP_REQUEST_STARTED',
    SUCCESS_GET_GROUP_REQUEST: 'SUCCESS_GET_GROUP_REQUEST',
    FAILURE_GET_GROUP_REQUEST: 'FAILURE_GET_GROUP_REQUEST',
    GET_GROUP_REQUEST_ENDED: 'GET_GROUP_REQUEST_ENDED',

    GET_GROUP_ADMINS_REQUEST_STARTED: 'GET_GROUP_ADMINS_REQUEST_STARTED',
    SUCCESS_GET_GROUP_ADMINS_REQUEST: 'SUCCESS_GET_GROUP_ADMINS_REQUEST',
    FAILURE_GET_GROUP_ADMINS_REQUEST: 'FAILURE_GET_GROUP_ADMINS_REQUEST',
    GET_GROUP_ADMINS_REQUEST_ENDED: 'GET_GROUP_ADMINS_REQUEST_ENDED',

    ADD_GROUP_ADMIN_REQUEST_STARTED: 'ADD_GROUP_ADMIN_REQUEST_STARTED',
    SUCCESS_ADD_GROUP_ADMIN_REQUEST: 'SUCCESS_ADD_GROUP_ADMIN_REQUEST',
    FAILURE_ADD_GROUP_ADMIN_REQUEST: 'FAILURE_ADD_GROUP_ADMIN_REQUEST',
    ADD_GROUP_ADMIN_REQUEST_ENDED: 'ADD_GROUP_ADMIN_REQUEST_ENDED',

    REMOVE_GROUP_ADMIN_REQUEST_STARTED: 'REMOVE_GROUP_ADMIN_REQUEST_STARTED',
    SUCCESS_REMOVE_GROUP_ADMIN_REQUEST: 'SUCCESS_REMOVE_GROUP_ADMIN_REQUEST',
    FAILURE_REMOVE_GROUP_ADMIN_REQUEST: 'FAILURE_REMOVE_GROUP_ADMIN_REQUEST',
    REMOVE_GROUP_ADMIN_REQUEST_ENDED: 'REMOVE_GROUP_ADMIN_REQUEST_ENDED',

    CREATE_SHORTURL_REQUEST_STARTED: 'CREATE_SHORTURL_REQUEST_STARTED',
    SUCCESS_CREATE_SHORTURL_REQUEST: 'SUCCESS_CREATE_SHORTURL_REQUEST',
    FAILURE_CREATE_SHORTURL_REQUEST: 'FAILURE_CREATE_SHORTURL_REQUEST',
    CREATE_SHORTURL_REQUEST_ENDED: 'CREATE_SHORTURL_REQUEST_ENDED',
    CLEAR_SHORTURL_STATE: 'CLEAR_SHORTURL_STATE'

}