export const userConstants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    TOKEN_AUTH_REQUEST: 'TOKEN_AUTH_REQUEST',
    TOKEN_AUTH_FAILURE: 'TOKEN_AUTH_FAILURE',
    TOKEN_AUTH_SUCCESS: 'TOEKN_AUTH_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    GET_MATCHING_USERS_REQUEST_STARTED: 'GET_MATCHING_USERS_REQUEST_STARTED',
    SUCCESS_GET_MATCHING_USERS_REQUEST: 'SUCCESS_GET_MATCHING_USERS_REQUEST',
    FAILURE_GET_MATCHING_USERS_REQUEST: 'FAILURE_GET_MATCHING_USERS_REQUEST',
    GET_MATCHING_USERS_REQUEST_ENDED: 'GET_MATCHING_USERS_REQUEST_ENDED',
}
